/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ciclos;


public class App {
    
    public static String Verde = "\u001B[32m",
        Rojo = "\u001B[31m",
        Negro = "\u001B[30m",
        Amarillo = "\u001B[33m",
        Azul = "\u001B[34m",
        Purpura = "\u001B[35m",
        CYAN = "\u001B[36m",
        Blanco = "\u001B[37m",
        RESET = "\u001B[0m";
    
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {

        try {
            
        } 
        
        catch (Exception e) {
            System.out.println("Ocurrió un error \n" + e);
            
        }


    }
}
