/*
 * This source file was generated by the Gradle 'init' task
 */
package _arreglos;
import java.text.DecimalFormat;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        try{
            DecimalFormat formato = new DecimalFormat("#.#");
            /* 
            //DECLARACION VECTOR CON TAMAÑO
            int[] v_valores = new int[10];

            //LO NORMAL ES USAR CICLOS FOR PARA ARREGLOS
            //LLENAR EL VECTOR CON ALEATORIOS
            for(byte pos = 0; pos < v_valores.length; pos++){
                v_valores[pos] = (int)(Math.random()*100000);

            }

            //RECORRER EL VECTOR E IMPRIMIR LOS ELEMENTOS

            for(byte pos = 0; pos < v_valores.length; pos++){
                System.out.print(v_valores[pos] + "\t");

            }
            System.out.println();
            for(byte pos = (byte)(v_valores.length-1); pos>=0; pos--){
                System.out.print(v_valores[pos] + "\t");
            }

            //MATRICES
            String[][] m_vehiculos = new String[3][4];

            boolean[][] m_tablero = {{true,false,false},
                                    {true,true,true},
                                    {false,true,false}};
         
            float[][] m_mediciones = {{(float)Math.random()*10, (float)Math.random()*10},
                                    {(float)Math.random()*10, (float)Math.random()*10},
                                    {(float)Math.random()*10, (float)Math.random()*10},
                                    {(float)Math.random()*10, (float)Math.random()*10},
                                    {(float)Math.random()*10, (float)Math.random()*10},
                                    };
                                    
            //RECORRER LA MATRIZ
            System.out.println();
            for(byte fil=0;fil<=m_mediciones.length-1;fil++){

                for(byte col = 0; col <= m_mediciones[0].length-1; col++){
                    System.out.print(formato.format(m_mediciones[fil][col]) + "\t");
                }
                System.out.println();
            }
            */
            
            //Rotación del vector
            String[] v_premios = {"Tv UHD 4.0 50¨ ", "Patineta Eléctirca", "PlayStation", "Portátil"};

            byte cant_rotaciones = 35;
            String aux = "";

            for (byte rot =1; rot <= cant_rotaciones; rot++){

                aux = v_premios[v_premios.length-1];

                for(byte pos = (byte)(v_premios.length-2); pos >=0; pos--){

                    v_premios[pos+1] = v_premios[pos];
                }

                v_premios[0] = aux;

                System.out.println("Rotación " + rot + "t" + v_premios.toString());
                System.out.println("Rotación " + rot + "t" + Arrays.toString(v_premios));

            }


        }
        catch(Exception error){
            System.out.println("Ocurrio un error " + error.toString());
        }
    }
}
