/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _condicionales;
import java.security.DrbgParameters.Reseed;
//zona de imports
import java.util.Scanner; //libreria para capturar datos desde la consola

import javax.security.sasl.AuthorizeCallback;

public class App {
    
    final static String Verde = "\u001B[32m",
    Rojo = "\u001B[31m",
    Negro = "\u001B[30m",
    Amarillo = "\u001B[33m",
    Azul = "\u001B[34m",
    Purpura = "\u001B[35m",
    CYAN = "\u001B[36m",
    Blanco = "\u001B[37m",
    RESET = "\u001B[0m";


    public static void main(String[] args){

        try {

            Scanner teclado = new Scanner(System.in);
            final byte n1=3,n2=5,n3=2;
            final float por = 0.25f;
            char nota_cual;
            float nota_eq =0, nota_fin = 0;
            String msg_error ="";

            System.out.println("Ingrese la nota cualitativa");
            nota_cual=teclado.nextLine().charAt(0);

            switch(nota_cual){
                case 'E': nota_eq=5;
                    break;
                case 'B': nota_eq=4;
                    break;
                case 'R': nota_eq=3;
                    break;
                case 'M': nota_eq=2;
                    break;
                case 'D': nota_eq=1;
                    break;
                default: msg_error = "Error en la nota cualitativa";
            }
            if(nota_eq > 0){
                nota_fin = n1*por+n2*por+n3*por+nota_eq*por;
                if(nota_fin>=3)
                    System.out.println(Verde+nota_fin);
                else
                    System.out.println(Rojo + nota_fin);
            }
            else
                System.out.println(msg_error);

            
            System.out.println(RESET);


        } 
        
        catch (Exception e) {
            System.out.println("Ocurrió un error \n" + e);
        }

    }
    



}

