/*
 * This source file was generated by the Gradle 'init' task
 */
package _archivos;
import  java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        try {
            
            //1. Ubicar el archivo con la ruta relativa del archivo
            File arc_nros = new File("Codigos\\4_Archivos\\app\\src\\main\\resources\\numeros.txt");

            //2. Abrir el archivo, en este caso de lectura
            FileReader abr_nros = new FileReader(arc_nros);

            //3. Ponemos el archivo en buffer correspondiente
            BufferedReader buf_nros = new BufferedReader(abr_nros);

            //4. leer la primera linea
            String linea = buf_nros.readLine();
            long total_suma = 0;

            //5. Preguntar si está vacío el archivo
            if(linea == null)
                System.out.println("Archivo está vacío");
            else{
                //Ciclo para operar el archivo
                while(linea != null){
                    total_suma+= Long.parseLong(linea);
                    linea = buf_nros.readLine(); //la instruccion que lee la siguiente linea, da continuidad al ciclo
                }

            }
            //6. Cerrar el archivo
            buf_nros.close();
            //7. Presentar los resultados
            System.out.println("La suma total fue de: " + total_suma);

        } 
        
        catch (Exception e) {
            System.out.println(e.toString());
        }



    }
}
