/*
 * This source file was generated by the Gradle 'init' task
 */
package _strings;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
                String email = "cesar.lopezg@upb.edu.co";

                //1. Declarar una cajita para recibir los pedazos del string
                String[] cajita;

                //2. Partir el string y lo vamos a poner en la cajita
                cajita = email.split("\\.");

                //3. Contar las partes o el tamaño de la cajita
                System.out.println(cajita.length);

                //4. recorrer la cajita
                for(int pos = 0; pos < cajita.length; pos++){
                    System.out.println(cajita[pos]);
                }


        } 
        
        catch (Exception e) {
            System.out.println("Error \n" + e);
        }
    }
}
