/*
 * This source file was generated by the Gradle 'init' task
 */
package _strings;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            String jugadas = "XOXXOOXXO", j_h="", j_v="";
            byte factor_h=0;

            for(byte i = 0; i<=jugadas.length()-1;i+=3){


                j_h = "" + jugadas.charAt(i*factor_h) + jugadas.charAt(i*factor_h+1) + jugadas.charAt(i*factor_h+2);


                System.out.println("Horizontal " + j_h);

                //j_v = "" + jugadas.charAt(i) + jugadas.charAt(i+3) + jugadas.charAt(i+6);
                //System.out.println("Vertical " + j_v);
                
                j_v=""; 
                j_h = "";
                factor_h++;
                

            }
        } 
        
        catch (Exception e) {
            System.out.println("Error \n" + e);
        }
    }
}
